services:
  immich-public-proxy:
    build: .
    container_name: immich-public-proxy
    restart: always
    ports:
      - "3000:3000"
    environment:
      IMMICH_URL: http://immich.homelab.local/
    healthcheck:
      test: curl -s http://localhost:3000/share/healthcheck -o /dev/null || exit 1
      start_period: 10s
      timeout: 5s
